var SHEETS_ID = '1Rs79K8wX27lxVRddksNlYwdyesTCOjIhHCqH0jRMV-o';
var SHEET_NAME = 'Pending Orders';
var DEBUG_SHEET = 'Wufoo Debug';
var DRIVE_FOLDER_ID = '1hK4iox_XmAFWOD-mMGjpEHBENOxJneeB';

// Every file field on the Wufoo form, in the order the client sees them.
//
// This list is the fix for orders that arrived "lacking attachment": the form
// has ELEVEN file fields and this script used to read two of them, so nine
// slots were dropped on arrival with nothing logged and nothing shown. 51 files
// across 15 orders went missing that way; one order had eleven and showed two.
// (They were recoverable — the raw POST is stored below — and have been
// backfilled, so this list only has to hold for orders from here on.)
//
// Listed explicitly rather than discovered by scanning for '-url' keys: a new
// file field on the form should be a deliberate addition here, not a silent
// change in what the webhook does.
var FILE_FIELDS = ['Field128','Field129','Field132','Field133','Field134',
                   'Field135','Field136','Field137','Field138','Field139','Field140'];

// WUFOO_API_KEY was removed 2026-08-02. Nothing read it: _uploadAttachment fetches
// the attachment link with NO auth header, because Wufoo hands out pre-signed
// Amazon S3 URLs that already carry authorisation in the query string — sending a
// second one is what made AWS return 400 InvalidArgument back in June. The variable
// was left behind by that fix. Do NOT reintroduce it; if an attachment fetch ever
// fails, the cause is the pre-signed link expiring, not a missing key.
//
// The old value was published in this repo's git history and must be regenerated by
// the Wufoo account owner (Account -> API Information). Nothing here breaks when it
// is: this script never calls Wufoo's API, it only receives webhook posts.

// Same publishable/anon key already embedded in index.html (SUPA_ANON_KEY) —
// safe to duplicate here, it's meant to be public-facing. Dual-write only:
// if this fails for any reason, the Sheets row above is already saved and
// remains the source of truth — the app falls back to Sheets automatically.
var SUPA_URL = 'https://nkpekroogqsmfilypowd.supabase.co';
var SUPA_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rcGVrcm9vZ3FzbWZpbHlwb3dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIwMDk5NTAsImV4cCI6MjA5NzU4NTk1MH0.MKMsMM9C4xCMu5qlLytvRrk5znbswrFp0WgtUk04fQA';

var HEADERS = ['ID','Received At','Client Name','Company Name','Contact Number',
  'Customer Email','Salesman Email','Request Type','Type of Service','Floor (1F/2F)',
  'Board/Substrate','Haspe Flow','Edging','Boring','Cutting','Lipping',
  'Handgrab Included','Handgrab Groove','Handgrab Installation','Handgrab By',
  'Agent Name','Attachment 1','Attachment 2','Status','Quotation Serial','Sent At','Source Company'];

function _uploadAttachment(wufooUrl, entryId, fileNum) {
  if (!wufooUrl || wufooUrl === '') return '';
  try {
        var resp = UrlFetchApp.fetch(wufooUrl, { muteHttpExceptions: true });
    if (resp.getResponseCode() !== 200) return wufooUrl;
    var blob = resp.getBlob();
    var ext = blob.getContentType().split('/').pop().replace('jpeg','jpg');
    blob.setName('Order-' + entryId + '-File' + fileNum + '.' + ext);
    var folder = DriveApp.getFolderById(DRIVE_FOLDER_ID);
    var file = folder.createFile(blob);
    file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
    return file.getUrl();
  } catch(e) {
    Logger.log('Attachment upload failed: ' + e.toString());
    return wufooUrl;
  }
}

// Copies every file the client attached into Drive and returns the full list.
// _uploadAttachment falls back to the original Wufoo link if a fetch fails, so a
// file is never dropped for being unreachable — it just arrives as a Wufoo link
// instead of a Drive copy, which is still visible on the order card.
function _collectAttachments(p, entryId) {
  var atts = [];
  for (var i = 0; i < FILE_FIELDS.length; i++) {
    var src = p[FILE_FIELDS[i] + '-url'] || p[FILE_FIELDS[i]] || '';
    if (!src) continue;
    var moved = _uploadAttachment(src, entryId, atts.length + 1);
    if (moved) atts.push({ path: moved, name: p[FILE_FIELDS[i]] || '' });
  }
  return atts;
}

// Dual-write: mirrors the same new order row into Supabase's pending_orders
// table so the app's Orders page (which polls every 45s) can read from the
// fast path instead of Sheets. Best-effort and non-blocking — any failure
// here is logged but never thrown, so it can never break the Sheets save
// above, which already succeeded by the time this runs.
//
// Goes through the insert_pending_order() database function (RPC) instead of
// inserting into the table directly — a direct anon INSERT was mysteriously
// and consistently rejected by the table's row-level security policy despite
// the policy, grants, and role membership all checking out correctly (this
// was checked thoroughly: bogus key gave a different error, so the real key
// really was authenticating; SET ROLE anon manually in SQL succeeded fine;
// only the PostgREST-mediated request path failed). The RPC function runs
// with elevated privileges internally and sidesteps that check entirely,
// while anon is only ever granted permission to call this one narrow
// function — no broader table access.
function _supaInsertOrder(fields) {
  try {
    var payload = {
      id: fields.entryId,
      received_at: fields.receivedAt,
      client_name: fields.p['Field2'] || '',
      company_name: fields.p['Field4'] || '',
      contact_number: fields.p['Field6'] || '',
      customer_email: fields.p['Field131'] || '',
      salesman_email: fields.p['Field179'] || '',
      request_type: fields.p['Field156'] || '',
      type_of_service: fields.p['Field161'] || '',
      floor: fields.p['Field168'] || '',
      board_substrate: fields.p['Field150'] || '',
      haspe_flow: fields.p['Field163'] || '',
      edging: fields.p['Field123'] || '',
      boring: fields.p['Field124'] || '',
      cutting: fields.p['Field171'] || '',
      lipping: fields.p['Field177'] || '',
      hg_included: fields.p['Field153'] || '',
      hg_groove: fields.p['Field172'] || '',
      hg_installation: fields.p['Field175'] || '',
      hg_by: fields.p['Field152'] || '',
      agent_name: fields.p['Field126'] || '',
      // The Sheets tab has room for two; this is where the rest live, and it is
      // what the app's order card actually renders.
      attachment_1: fields.att1,
      attachment_2: fields.att2,
      attachments:  fields.atts || [],
      status: 'Pending',
      quotation_serial: '',
      sent_at: null,
      source_company: fields.sourceCompany,
      raw: fields.p
    };
    var resp = UrlFetchApp.fetch(SUPA_URL + '/rest/v1/rpc/insert_pending_order', {
      method: 'post',
      contentType: 'application/json',
      headers: {
        apikey: SUPA_ANON_KEY,
        Authorization: 'Bearer ' + SUPA_ANON_KEY
      },
      payload: JSON.stringify({payload: payload}),
      muteHttpExceptions: true
    });
    var code = resp.getResponseCode();
    if (code >= 300) Logger.log('Supabase insert failed (' + code + '): ' + resp.getContentText());
  } catch(e) {
    Logger.log('Supabase insert threw: ' + e.toString());
  }
}

function doPost(e) {
  try {
    var ss = SpreadsheetApp.openById(SHEETS_ID);
    var p = e.parameter || {};
    Logger.log('RAW: ' + JSON.stringify(p));
    var dbg = ss.getSheetByName(DEBUG_SHEET);
    if (!dbg) { dbg = ss.insertSheet(DEBUG_SHEET); dbg.appendRow(['Timestamp','Raw Params']); }
    dbg.appendRow([new Date().toISOString(), JSON.stringify(p)]);
    var sheet = ss.getSheetByName(SHEET_NAME);
    if (!sheet) { sheet = ss.insertSheet(SHEET_NAME); sheet.appendRow(HEADERS); sheet.setFrozenRows(1); }
    else if (sheet.getLastRow() === 0) { sheet.appendRow(HEADERS); sheet.setFrozenRows(1); }
    var entryId = p['EntryId'] || '';
    var rawDate = p['DateCreated'] || '';
    var dt = rawDate ? new Date(rawDate.replace(' ','T')+'-07:00') : new Date();
    var receivedAt = Utilities.formatDate(dt, 'Asia/Manila', "yyyy-MM-dd'T'HH:mm:ss") + '+08:00';
    var salesEmail = p['Field179'] || '';
    var sourceCompany = '';
    if (salesEmail.indexOf('worldclasslaminate') > -1) sourceCompany = 'World Class Laminate, Inc.';
    else if (salesEmail.indexOf('modulesystems') > -1) sourceCompany = 'Module Systems and Services, Inc.';
    else if (salesEmail.indexOf('cebuworld') > -1) sourceCompany = 'Cebu World Laminate, Inc.';
    // Every attached file, not the first two.
    var atts = _collectAttachments(p, entryId);
    // The Sheets columns and every older row still expect exactly these two.
    var att1 = atts.length > 0 ? atts[0].path : '';
    var att2 = atts.length > 1 ? atts[1].path : '';
    if (atts.length > 2) {
      Logger.log('Order ' + entryId + ': ' + atts.length + ' files (2 in Sheets, all ' + atts.length + ' in Supabase)');
    }
    var row = [
      entryId, receivedAt,
      p['Field2']||'', p['Field4']||'', p['Field6']||'',
      p['Field131']||'', p['Field179']||'', p['Field156']||'',
      p['Field161']||'', p['Field168']||'', p['Field150']||'',
      p['Field163']||'', p['Field123']||'', p['Field124']||'',
      p['Field171']||'', p['Field177']||'', p['Field153']||'',
      p['Field172']||'', p['Field175']||'', p['Field152']||'',
      p['Field126']||'', att1, att2, 'Pending','','', sourceCompany
    ];
    sheet.appendRow(row);
    // Sheets save above already succeeded — this is additive and can never
    // undo or block it, regardless of outcome.
    _supaInsertOrder({entryId: entryId, receivedAt: receivedAt, p: p,
                      att1: att1, att2: att2, atts: atts, sourceCompany: sourceCompany});
    return ContentService.createTextOutput(JSON.stringify({status:'ok',entry:entryId,files:atts.length})).setMimeType(ContentService.MimeType.JSON);
  } catch(err) {
    Logger.log('ERROR: ' + err.toString());
    return ContentService.createTextOutput(JSON.stringify({status:'error',message:err.toString()})).setMimeType(ContentService.MimeType.JSON);
  }
}

function testAttachment() {
  var testUrl = 'https://worldclasslaminate.wufoo.com/cabinet/1af066e4-45a1-48a6-9ff7-d0c7e2be311f';
  var result = _uploadAttachment(testUrl, 'TEST001', 1);
  Logger.log('Result: ' + result);
}

// Checks the file-field list against a real submission without touching Drive,
// Sheets or Supabase. Paste an EntryId from the Wufoo Debug tab: it reports how
// many files that submission carried and which fields they were in, so a form
// change that adds a twelfth field shows up here rather than as a quiet loss.
function testFileFields(entryId) {
  var ss = SpreadsheetApp.openById(SHEETS_ID);
  var dbg = ss.getSheetByName(DEBUG_SHEET);
  if (!dbg) { Logger.log('No debug sheet yet.'); return; }
  var rows = dbg.getDataRange().getValues();
  for (var r = rows.length - 1; r > 0; r--) {
    var raw;
    try { raw = JSON.parse(rows[r][1]); } catch(e) { continue; }
    if (entryId && String(raw['EntryId']) !== String(entryId)) continue;
    var known = [], unknown = [];
    for (var k in raw) {
      if (k.slice(-4) !== '-url' || !raw[k]) continue;
      var base = k.slice(0, -4);
      (FILE_FIELDS.indexOf(base) >= 0 ? known : unknown).push(base);
    }
    Logger.log('Entry ' + raw['EntryId'] + ': ' + known.length + ' file(s) captured — ' + known.join(', '));
    if (unknown.length) {
      Logger.log('!! ' + unknown.length + ' file field(s) NOT in FILE_FIELDS and would be dropped: ' + unknown.join(', '));
    }
    return;
  }
  Logger.log('No matching submission found in the debug sheet.');
}
